from django_assets import Bundle, register

cssdev = Bundle('stylesheets/application.css',
                'main/css/ui.jqgrid.css',
                'libs/jbar/css/jbar.css',
                'main/css/bootstrap-jqui/jquery-ui-1.10.0.custom.css',
                'main/css/dropzone.css',
                'main/css/bootstrap-lightbox.min.css',
                'django_facebook/css/facebook.css')

jsdev = Bundle('main/js/template.js',
               'http://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=drawing',
               'http://ecn.dev.virtualearth.net/mapcontrol/mapcontrol.ashx?v=6.2&mkt=en-us',
               'main/js/libs/proj4js-compressed.js',
               'main/js/libs/OpenLayers-2.11/OpenLayers.js',
               'http://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.3.1/jquery.cookie.min.js',
               'http://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js',
               'http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.4.4/underscore-min.js',
               'http://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.0.0/backbone-min.js',
               'http://cdnjs.cloudflare.com/ajax/libs/jquery-scrollTo/1.4.5/jquery.scrollTo.min.js',
               'http://cdnjs.cloudflare.com/ajax/libs/bootstrap-lightbox/0.6.1/bootstrap-lightbox.js',
               'main/js/libs/jquery.MultiFile.js',
               'main/js/libs/jquery.jqGrid.min.js',
               'libs/jbar/jquery.bar.js',
               'main/js/libs/dropzone.js',
               'main/js/libs/jquery.cutetime.js',
               'main/js/libs/bootbox.min.js',
               'libs/markerclusterer.js',
               'libs/jquery.linkedsliders.js',
               'libs/rainbowvis.js',
               'main/js/messages/feed.js',
               'main/js/models/User.js',
               'main/js/models/Users.js',
               'main/js/models/Category.js',
               'main/js/models/Element.js',
               'main/js/models/Schema.js',
               'main/js/models/Occurrence.js',
               'main/js/models/Shapes.js',
               'main/js/models/Followers.js',
               'main/js/models/Groups.js',
               'main/js/models/HopeUser.js',
               'main/js/controllers/ProjectsController.js',
               'main/js/controllers/UsersController.js',
               'main/js/views/FindReports/MapHandler.js',
               'main/js/views/FindReports/GmapHandler.js',
               'main/js/views/FindReports/FindReportsView.js',
               'main/js/views/Reports/DrawingHandler.js',
               'main/js/views/Reports/ReportView.js',
               'main/js/views/Reports/ReportFormView.js',
               'main/js/views/Profile/ProfileView.js',
               'main/js/views/Manage/ManageView.js',
               'main/js/views/DecisionSupport/DecisionView.js',
               'main/js/views/Reports/TOcMapView.js',
               'main/js/views/Groups/GroupsView.js',
               'main/js/common.js',
               'main/js/application.js')


css = Bundle('stylesheets/application.css',
             'main/css/ui.jqgrid.css',
             'libs/jbar/css/jbar.css',
             'main/css/bootstrap-jqui/jquery-ui-1.10.0.custom.css',
             'main/css/dropzone.css',
             'main/css/bootstrap-lightbox.min.css',
             'django_facebook/css/facebook.css',
             filters='cssmin', output='gen/packed.css')

js = Bundle('main/js/template.js',
            'http://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=drawing',
            'http://ecn.dev.virtualearth.net/mapcontrol/mapcontrol.ashx?v=6.2&mkt=en-us',
            'main/js/libs/proj4js-compressed.js',
            'main/js/libs/OpenLayers-2.11/OpenLayers.js',
            'http://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.3.1/jquery.cookie.min.js',
            'http://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js',
            'http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.4.4/underscore-min.js',
            'http://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.0.0/backbone-min.js',
            'http://cdnjs.cloudflare.com/ajax/libs/jquery-scrollTo/1.4.5/jquery.scrollTo.min.js',
            'http://cdnjs.cloudflare.com/ajax/libs/bootstrap-lightbox/0.6.1/bootstrap-lightbox.js',
            'main/js/libs/jquery.MultiFile.js',
            'main/js/libs/jquery.jqGrid.min.js',
            'libs/jbar/jquery.bar.js',
            'main/js/libs/dropzone.js',
            'main/js/libs/jquery.cutetime.js',
            'main/js/libs/bootbox.min.js',
            'libs/markerclusterer.js',
            'libs/jquery.linkedsliders.js',
            'libs/rainbowvis.js',
            'main/js/messages/feed.js',
            'main/js/models/User.js',
            'main/js/models/Users.js',
            'main/js/models/Category.js',
            'main/js/models/Element.js',
            'main/js/models/Schema.js',
            'main/js/models/Occurrence.js',
            'main/js/models/Shapes.js',
            'main/js/models/Followers.js',
            'main/js/models/Groups.js',
            'main/js/models/HopeUser.js',
            'main/js/controllers/ProjectsController.js',
            'main/js/controllers/UsersController.js',
            'main/js/views/FindReports/MapHandler.js',
            'main/js/views/FindReports/GmapHandler.js',
            'main/js/views/FindReports/FindReportsView.js',
            'main/js/views/Reports/DrawingHandler.js',
            'main/js/views/Reports/ReportView.js',
            'main/js/views/Reports/ReportFormView.js',
            'main/js/views/Profile/ProfileView.js',
            'main/js/views/Manage/ManageView.js',
            'main/js/views/DecisionSupport/DecisionView.js',
            'main/js/views/Reports/TOcMapView.js',
            'main/js/views/Groups/GroupsView.js',
            'main/js/common.js',
            'main/js/application.js',
            filters='jsmin', output='gen/packed.js')

register('js_all', js)
register('css_all', css)

# dev
register('css_dev', cssdev)
register('js_dev', jsdev)
